### PR TITLE
readme file changed and all finalized

### PR DESCRIPTION
**Pull request by sumancrest0001**
Authentication System is created following the guidelines.
1. User authentication system.
2. Post can be created.
3. Author is only visible for logged in users.

### CODE REVIEW

**Comment by maelfosso** [comment]
# Changes required

Hello @sumancrest0001 @noomdalv 

Thank you very much for that original UX and UI experience :+1: 
While it's working, your code has some issues. 

1. https://github.com/noomdalv/rails_authentication/blob/293506dc73b203e8e55c0150a0d5feab51ee591b/app/helpers/application_helper.rb#L13
Try to not use `session`. Think about using `:remember_token` and cookies

2. https://github.com/noomdalv/rails_authentication/blob/293506dc73b203e8e55c0150a0d5feab51ee591b/app/helpers/application_helper.rb#L19
Can be done in oneline. Just by checking whether or not the user with the remember token exists

3.  https://github.com/noomdalv/rails_authentication/blob/293506dc73b203e8e55c0150a0d5feab51ee591b/app/controllers/sessions_controller.rb#L9-L10
Should be merged in one method. Only sign in.

4. https://github.com/noomdalv/rails_authentication/blob/293506dc73b203e8e55c0150a0d5feab51ee591b/app/controllers/posts_controller.rb#L4
I don't think that is enough. Did you try to access directly to the route `http://localhost:3000/posts/new`? How do you solve the error ?

5. 
https://github.com/noomdalv/rails_authentication/blob/293506dc73b203e8e55c0150a0d5feab51ee591b/app/views/posts/index.html.erb#L12-L14
The `user` variable create is not needed. You could directly use the `user` attribute from `Post` class directly.

Kindly make the changes and submit a new code review request.
Thanks

**Mael FOSSO**
[Github](https://github.com) | [Twitter](https://twitter.com) | [LinkedIn](https://www.linkedin.com/in/mael-elvis-fosso-650b6346/)

**Comment by noomdalv** [comment]
Corrections done, ready for review:

Changelog:
1. Merged #sign_in and remember methods so users can have a session id and cookies assigned when a session is created

2. fixed #current_user method, should return current_user correctly

3. route to /posts/new should be working properly now for non signed in users

**Comment by samgaco** [comment]
Hi @sumancrest0001 and @noomdalv :high_brightness: 

Please avoid this kind of logic in the views as @maelfosso  pointed out, you should be able to access to the user of this post from the association. Something similar to `Post.user`
> https://github.com/noomdalv/rails_authentication/blob/293506dc73b203e8e55c0150a0d5feab51ee591b/app/views/posts/index.html.erb#L12-L14
> 
> 
> The `user` variable create is not needed. You could directly use the `user` attribute from `Post` class directly.


The rest of the things were well implemented. Please address that last point and submit back for another review :+1: 


----------------------

* ###### STATUS OF THE PROJECT: REQUESTED CHANGES :stop_sign:

**Comment by noomdalv** [comment]
Reference to Author of posts in index corrected, it should point to post.user.name now

**Review by efrapp — APPROVED** [review]
## Hi @sumancrest0001 and @noomdalv 👋

Great job guys, you completed the suggestions from the previous code review so you can merge the PR. 👍

As an additional suggestion, please, add a `.ruby-version` file to your project in that way other people can use the same version you are using locally.

Have a great day!

**Status:** `Approved`

**Pull request merged**
